[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=1

monitor_speed = 921600
board_build.partitions = huge_app.csv

lib_deps = 
    https://github.com/espressif/esp32-camera.git

upload_speed = 921600

upload_flags = 
    --before=default_reset
    --after=hard_reset

monitor_rts = 0
monitor_dtr = 0
