blank_issues_enabled: false
contact_links:
  - name: 📧 Контактная информация проекта
    url: https://github.com/laureatbarbie-eng/CloudCam
    about: Посетите репозиторий проекта для получения дополнительной информации.